# https://taskfile.dev

version: '3'

tasks:
  start:
    cmds:
      - go run ./cmd
  start-dev:
    cmds:
      - reflex -r '\.go$' -d none -s -- sh -c 'clear && go run ./cmd'

  log-service: watch -n 0.5 'cat /tmp/log 2>&1 | grep --line-buffered {{.CLI_ARGS}} | jq' 
